version: '3.8'

services:
  pippin:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./my_digital_being:/app/my_digital_being
    environment:
      - PYTHONUNBUFFERED=1
      - COMPOSIO_API_KEY=${COMPOSIO_API_KEY:-}
    working_dir: /app/my_digital_being
    command: python server.py
    # Uncomment below to use CLI instead of web UI
    # command: python -m framework.main

  # Optional: Add a development container
  pippin-dev:
    build: .
    volumes:
      - .:/app
      - ./config:/app/config
    environment:
      - PYTHONUNBUFFERED=1
    command: python -m tools.onboard
    profiles:
      - dev